kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: topic #we can give any name here
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: topic #key should match with key in nginx-config
    - name: cloud
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: cloud #key should match with key in nginx-config
